# Generated by Django 5.0.2 on 2024-02-29 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('string', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AdPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default='b.d.', max_length=30)),
                ('full_name', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('title', models.CharField(default='b.d.', max_length=60)),
                ('department', models.CharField(default='b.d.', max_length=80)),
                ('office', models.CharField(default='b.d.', max_length=80)),
                ('manager', models.CharField(default='b.d.', max_length=100)),
                ('emailaddress', models.CharField(default='b.d.', max_length=50)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_id', models.IntegerField(default=10000)),
                ('manager_first_name', models.CharField(max_length=30)),
                ('manager_last_name', models.CharField(max_length=40)),
                ('person_first_name', models.CharField(max_length=30)),
                ('person_last_name', models.CharField(max_length=40, verbose_name='nazwisko użytkownika')),
                ('request_time', models.DateTimeField()),
                ('accept_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['display_id'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='b.d.', max_length=80)),
                ('office', models.CharField(default='b.d.', max_length=80)),
            ],
            options={
                'ordering': ['office', 'name'],
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=60)),
                ('server_name', models.CharField(max_length=60, null=True)),
                ('database', models.CharField(max_length=60, null=True)),
                ('login', models.CharField(max_length=30, null=True)),
                ('password', models.CharField(max_length=30)),
                ('port', models.CharField(max_length=6, null=True)),
                ('db_type', models.CharField(choices=[('fb', 'Firebird'), ('MS', 'MS SQL Server'), ('PS', 'Powershell'), ('CS', 'CSV file'), ('YA', 'yaml file')], max_length=8)),
                ('sql_query_roles', models.TextField()),
                ('sql_query_accounts', models.TextField()),
                ('sql_query_accounts_roles', models.TextField()),
                ('update_time', models.DateTimeField(null=True)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Commission_role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=60)),
                ('role_name', models.CharField(max_length=60)),
                ('role_internal_id', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('+', 'dodane'), ('-', 'usunięte'), ('=', 'bez zmian')], default='=', max_length=2)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syspriv.commission')),
            ],
            options={
                'ordering': ['system_name', 'role_name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=500)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syspriv.system')),
            ],
            options={
                'ordering': ['system', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(max_length=40)),
                ('login', models.CharField(max_length=80)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('adperson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='syspriv.adperson')),
                ('roles', models.ManyToManyField(related_name='accounts', to='syspriv.role')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syspriv.system')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
