# Generated by Django 5.0.2 on 2024-03-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syspriv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='systems',
            field=models.ManyToManyField(to='syspriv.system'),
        ),
    ]
